# -*- coding: utf-8 -*-
"""Tarea4ok.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KGpYwibp2j9-3qveZyNfSc4QTbAr-Lj2
"""

##primero instalamos las librerias necesarias
!pip install --target=$nb_path nacal
from nacal import *
from IPython.display import display, Math, Latex

"""PRIMERO INICIALIZAMOS LAS LIBRERIAS

### Primer ejercicio

Cree la matriz
$${A}=\begin{bmatrix}1&0&0&0\\2&0&0&0\\0&3&3&0\\0&3&4&1\\0&1&2&1\end{bmatrix}$$
"""

a=( [1, 0, 0, 0] )
b=( [2, 0, 0,0] )
c=( [0,3,3,0] )
d=( [0,3,4,1] )
e=( [0,1,2,1] )
mat=Matrix( [a, b, c, d,e] )
display(Latex(latex(mat)))

"""Cree a partir de ${A}$ una matriz cuya única columna sea la
primera columna de ${A}$


"""

a1=( [1] )
b1=( [2] )
c1=( [0] )
d1=( [0] )
e1=c=( [0] )
mat1=Matrix( [a1, b1, c1, d1,e1] )
display(Latex(latex(mat1)))

"""Cree a partir de ${A}$ una matriz cuya única columna sea la segunda
fila de ${A}$


"""

a2=( [0] )
b2=( [0] )
c2=( [3] )
d2=( [3] )
e2=c=( [1] )
mat2=Matrix( [a2, b2, c2, d2,e2] )
display(Latex(latex(mat2)))

"""<div class="EXERCISE">
Cree a partir de $A$ una matriz cuya única fila sea la primera
fila de $A$

</div>


"""

a3=( [1,0,0,0] )
mat3=Matrix( [a] )
display(Latex(latex(mat3)))

"""### Segundo ejercicio

Calcule el siguiente vector: 3 veces la primera columna de $A$
menos la segunda columna de $A$ mas 2 veces la tercera columna
menos 3 veces la última columna de $A$
"""

a11=( [0] )
b11=( [0] )
c11=( [3] )
d11=( [4] )
e11=( [2] )
mat11=Matrix( [a11, b11, c11, d11,e11] )
display(Latex(latex(mat11)))

a12=( [0] )
b12=( [0] )
c12=( [0] )
d12=( [1] )
e12=( [1] )
mat12=Matrix( [a12, b12, c12, d12,e12] )
display(Latex(latex(mat12)))

display(Latex(latex(((3*mat1)-(mat2))+((2*mat11)-(3*mat12)))))

"""### Tercer ejercicio

Proporcione ejemplos de matrices 3 por 3 no nulas de los siguientes
tipos de matrices:

-   Una matriz diagonal
"""

a4=( [-8, 1, 3] )
b4=( [1, 7, 4] )
c4=( [3, 4, 9] )
mat4=Matrix( [a4, b4, c4] )
display(Latex(latex(mat4)))

"""-   Una matriz simétrica


"""

a5=( [1, 0, 0] )
b5=( [0, 2, 0] )
c5=( [0, 0, 3] )
mat5=Matrix( [a5, b5, c5] )
display(Latex(latex(mat5)))

"""-   Una matriz triangular superior (es decir, que todos los elementos
    por *debajo* de la diagonal son nulos).


"""

a6=( [1, 3, 5] )
b6=( [0, 2, 3] )
c6=( [0, 0, 3] )
mat6=Matrix( [a6, b6, c6] )
display(Latex(latex(mat6)))

"""-   Una matriz antisimétrica (es decir, que su transpuesta es igual a su opuesta: $ {A}^{T}=-A $ ).


"""

a10=( [0, -2, 4] )
b10=( [2, 0, 2] )
c10=( [-4, -2, 0] )
mat10=Matrix( [a10, b10, c10] )
display(Latex(latex(mat10)))

"""### Cuarto ejercicio

# Propiedades del producto Matriz por vector

Genere una matriz $A$ (con el número de filas y columnas que
desee) y dos vectores ${b}$ y ${c}$ con tantos componentes
como columnas tenga $A$.
"""

# Defina una matriz A
a7=( [9, 3, 5] )
b7=( [1, 2, 8] )
c7=( [3, 0, 9] )
mat7=Matrix( [a7, b7, c7] )
display(Latex(latex(mat7)))

# Defina el vector b con tantos componentes como columnas tenga la matriz A
av=( [9] )
bv=( [5] )
cv=( [1] )
vec=Matrix( [av, bv, cv] )
display(Latex(latex(vec)))

# Defina el vector c con tantos componentes como el vector b
av2=( [2] )
bv2=( [8] )
cv2=( [3] )
vec2=Matrix( [av2, bv2, cv2] )
display(Latex(latex(vec2)))

"""Y ahora verifique las propiedades vistas en el curso (en todos los
casos, verifique sus ejemplos también con lapiz y papel... recuerde
que primero se realizan las operaciones encerradas entre paréntesis).

$$ A({b}+{c}) = A{b} + A{c} $$
"""

# escriba aquí la parte izquierda de la ecuación: A*(b+c)
display(Latex(latex(mat7*(vec+vec2))))

# escriba aquí la parte derecha de la ecuación
display(Latex(latex((mat7*vec)+(mat7*vec2))))

"""Tanto por el lado de la derecha y de la izquierda el resultado es el mismo
por lo tanto cumple las propiedades

### Quinto ejercicio

Decida un valor para el escalar $\lambda$ y verifique que
$$ A(\lambda{b}) = \lambda(A{b})$$
"""

# escriba aquí la parte izquierda de la ecuación
esc_lambda = 5
display(Latex(latex(mat7*(5*vec2))))

# escriba aquí la parte derecha de la ecuación
display(Latex(latex(5*(mat7*vec2))))

"""el resultado es el mismo por lo tanto se cumple las propiedades

Verifique que
$$ A(\lambda{b}) = (\lambda A){b}$$
"""

# escriba aquí la parte derecha de la ecuación
display(Latex(latex((5*mat7)*vec2)))

"""Compuebe que en este caso no son necesarios los paréntesis:
$$\lambda A{b}\;$$ (aunque en Python siempre necesite
escribir los símbolos de producto `*`). Pruebe a colocar el escalar en
cualquier posición, pero mantenga la matriz a la izquierda del vector.
"""

# Por ejemplo 3*A*b, o A*3*b, o A*b*3
display(Latex(latex(5*mat7*vec2)))

"""### Sexto ejercicio

Genere una matriz ${B}$ del mismo orden que $A$
"""

# Defina una matriz B
a8=( [8, 3, 7] )
b8=( [1, 0, 0] )
c8=( [2, 0, 4] )
mat8=Matrix( [a8, b8, c8] )
display(Latex(latex(mat8)))

"""Verifique que

$$ (A+B){c} = A{c} + B{c}$$
"""

# escriba aquí la parte izquierda de la ecuación (¿funciona sin paréntesis?)
display(Latex(latex((mat7+mat8)*vec2)))

# escriba aquí la parte derecha de la ecuación
display(Latex(latex((mat7*vec2)+(mat8*vec2))))

"""esa propiedad solo funcioina cuando la parte izquierda de la ecuación tiene paréntesis
no funciona sin el paréntesis

# Dos propiedades de la transposición

Recuerde que `~A` es la transpuesta de `A`.

Verfique que
$$
(A+B)^T=A^{T}+B^{T}
$$
"""

# escriba aquí la parte izquierda de la ecuación: ~(A + B)
display(Latex(latex(~(mat7+mat8))))

# escriba aquí la parte derecha de la ecuación
display(Latex(latex(~mat7+~mat8)))

"""se cumplen las propiedades por lo tal se comprueba la propiedad

¿Necesitamos usar paréntesis para el lado izquierdo? ¿Y para el derecho?

Decida un valor para $\lambda$ y verfique que
$$
(\lambda A)^T=\lambda(A^{T})
$$
"""

# escriba aquí la parte izquierda de la ecuación:
display(Latex(latex(~(2*mat7))))

# escriba aquí la parte derecha de la ecuación
display(Latex(latex(2*(~mat7))))

"""da el mismo resultado por lo cual cumple con las propiedades por la derecha y por la izquierda"""